services:
  - type: web
    name: finguide-frontend
    env: static
    rootDir: frontend/finguide
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
